affiliates_connect_ebay.settings:
  type: config_object
  label: 'Affiliates Connect Ebay settings'
  mapping:
    locale:
      type: string
      label: 'Location'
    native_api:
      type: boolean
      label: 'Allows usage Affiliate Marketing using tracking ID'
    ebay_app_id:
      type: string
      label: 'App Id from ebay developer program'
    service_endpoint:
      type: string
      label: 'Select service endpoint'
    search:
      type: boolean
      label: 'Allows searching of products'
    data_storage:
      type: boolean
      label: 'Allows storing product data in your site database'
    full_content:
      type: boolean
      label: 'Allows updating of full content'
    price:
      type: boolean
      label: 'Allows updating of price'
    available:
      type: boolean
      label: 'Allows updating of products availability'
    size:
      type: boolean
      label: 'Allows updating of size'
    color:
      type: boolean
      label: 'Allows updating of color'
    offers:
      type: boolean
      label: 'Allows updating of offers'
